version: '2'

services:
  fuseki:
    image: fcore/jena:0.1.4
    #   labels:
    #  - "traefik.backend=fuseki"
    #  - "traefik.port=3030"
    #  - "traefik.frontend.rule=Host:${HOST_NAME};PathPrefix:/blazegraph"
    restart: on-failure
    ports:
       - "3030:3030"
    volumes:
       - /home/fils/Data/OCDDataVolumes/jena/data:/data
    networks:
       - facility_default
    command: ["./fuseki-server", "--config=settings.ttl"]

  minio:
    image: minio/minio:latest
    ports:
       - 9000:9000
    environment:
       - SERVICE_PORTS=9000
       - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
       - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
       - ${DATAVOL}/s3/data:/data
       - ${DATAVOL}/s3/config:/root/.minio
    networks:
       - web
    command: ["server", "/data"]

networks:
  facility_default:
