version: "2"

services:
   fuseki:
      image: fcore/jena:0.1.8
      #   labels:
      #  - "traefik.backend=fuseki"
      #  - "traefik.port=3030"
      #  - "traefik.frontend.rule=Host:${HOST_NAME};PathPrefix:/blazegraph"
      restart: on-failure
      ports:
         - "3030:3030"
      volumes:
         - /home/fils/Data/OCDDataVolumes/jena/data:/data
      networks:
         - facility_default
      command: ["./fuseki-server", "--config=settings.ttl"]

   provisium:
      image: esip/provisium:0.2.0
      ports:
         - 6789:6789
      environment:
         - MINIO_HOST=${MINIO_HOST}
         - MINIO_PORT=${MINIO_PORT}
         - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
         - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      networks:
         - facility_default
      command: ["provisium"]

   minio:
      image: minio/minio:latest
      ports:
         - 9000:9000
      environment:
         - SERVICE_PORTS=9000
         - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
         - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      volumes:
         - ${DATAVOL}/s3/data:/data
         - ${DATAVOL}/s3/config:/root/.minio
      networks:
         - facility_default
      command: ["server", "/data"]

networks:
   facility_default:
